version: '3.1'
services:
  article-app:
    container_name: article-app
    build: .
    volumes:
      - .:/var/www/html

    ports:
      - "9000:80"

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  