version: '3.1'
services:
  article-be-app:
    container_name: article-be-app
    build: .
    volumes:
      - .:/var/www/html

    ports:
      - "9002:80"

  mysql:
    image: mysql:latest
    container_name: article-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

