version: '3'
services:
  article-be-app:
    container_name: article-be-app
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html  # Mount your Laravel project directory to /var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public  # Set the Apache document root to /var/www/html/public
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${DB_DATABASE}
    networks: article-be-app
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: ${DB_HOST}
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    networks: article-be-app
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html  # Mount your Laravel project directory to /var/www/html
    working_dir: /var/www/html
    entrypoint: ["docker-php-entrypoint"]
    command: ["php", "artisan", "migrate"]
    networks: article-be-app
    depends_on:
      - mysql
      
  laravel-serve:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8035:8000"
    volumes:
      - .:/var/www/html  # Mount your Laravel project directory to /var/www/html
    working_dir: /var/www/html
    command: ["php", "artisan", "serve"]
    networks: article-be-app
networks:
  article-be-app:
    name: article-be-app
