version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: inister
      MYSQL_DATABASE: inister
      MYSQL_USER: inister
      MYSQL_PASSWORD: inister
    ports:
      - "3306:3306"
    networks:
      - laravel-net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - laravel-net
networks:
  laravel-net:
